## Discrete entropy 

In [56]:
import autograd.numpy as np
from scipy.stats import entropy as entropy_scipy

def expectation(f, x, p):
    return np.sum(p * f(x))

p = np.array([0.03, 0.12, 0.31, 0.21, 0.09, 0.24])
entropy_f = lambda x: -np.log(p[x])
entropy = lambda p: expectation(entropy_f, np.arange(len(p)), p)
entropy(p), entropy_scipy(p)

(1.609654142797407, 1.609654142797407)

In [31]:
import autograd

autograd.grad(entropy)(p)

array([3.5065579 , 2.12026354, 1.17118298, 1.56064775, 2.40794561,
       1.42711636])

In [54]:
def mc_expectation(f, x, p, n_samples=1):
    samples = np.random.choice(x, p=p, size=n_samples)
    return np.mean(f(samples))

mc_expectation(entropy_f, np.arange(len(p)), p, n_samples=int(1e5))

1.607948694711658

In [84]:
autograd.elementwise_grad(np.log)(np.array([1., 2., 3.]))

array([1.        , 0.5       , 0.33333333])

In [119]:
import pandas as pd

pd.Series(np.random.choice(len(p), p=p, size=1000)).value_counts()

2    326
5    248
3    183
1    128
4     92
0     23
dtype: int64

In [120]:
int(1e3)

1000

In [112]:
def score_function_estimator(f, x, p, n_samples=1):
    sample_indices = np.random.choice(len(x), p=p, size=n_samples)
    samples = x[sample_indices]
    log_p_f = lambda indices, p: np.log(p[indices])
    log_p_f_jac = autograd.jacobian(log_p_f, argnum=1)(sample_indices, p)
    sample_vals = log_p_f_jac * samples[:, np.newaxis]
    return np.mean(sample_vals, axis=0), np.std(sample_vals, axis=0)

score_function_estimator(entropy_f, np.arange(len(p)), p, n_samples=int(1e3))

(array([0.        , 1.01666667, 2.00645161, 3.17142857, 3.55555556,
        5.0625    ]),
 array([ 0.        ,  2.72738173,  2.98646966,  5.93701636, 12.05747553,
         8.93531442]))